- type: job
  id: Quartermaster
  name: Mine Supervisor
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  weight: 10
  startingGear: QuartermasterGear
  icon: "QuarterMaster"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: "CentCom"
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatQMsoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetCommand
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
